export const data = [
  {
    id: '1',
    product_category: 'Handbags',
    brand: 'Louis Vuitton',
    model: 'Neverfull MM',
    condition: 'Used - Good',
    price: '$1200',
    image: require('../assets/Louis-Vuitton.jpeg'),
  },
  {
    id: '2',
    product_category: 'Handbags',
    brand: 'Chanel',
    model: 'Classic Flap Bag',
    condition: 'Used - Excellent',
    price: '$5000',
    image: require('../assets/chanel_classic_flap_bag.jpeg'),
  },
  {
    id: '3',
    product_category: 'Laptops',
    brand: 'Apple',
    model: 'MacBook Pro',
    condition: 'New',
    price: '$2500',
    image: require('../assets/apple_macbook_pro.jpeg'),
  },
  {
    id: '4',
    product_category: 'Laptops',
    brand: 'Dell',
    model: 'XPS 13',
    condition: 'Used - Very Good',
    price: '$1500',
    image: require('../assets/dell_xps_13.jpeg'),
  },
  {
    id: '5',
    product_category: 'Smartphones',
    brand: 'Samsung',
    model: 'Galaxy S21',
    condition: 'New',
    price: '$999',
    image: require('../assets/samsung_galaxy_s21.jpeg'),
  },
  {
    id: '6',
    product_category: 'Smartphones',
    brand: 'Apple',
    model: 'iPhone 13',
    condition: 'New',
    price: '$1099',
    image: require('../assets/apple_iphone_13.jpeg'),
  },
  {
    id: '7',
    product_category: 'Televisions',
    brand: 'Sony',
    model: 'Bravia X90J',
    condition: 'New',
    price: '$1300',
    image: require('../assets/sony_bravia_x90j.jpeg'),
  },
  {
    id: '8',
    product_category: 'Televisions',
    brand: 'Samsung',
    model: 'QLED Q60T',
    condition: 'New',
    price: '$900',
    image: require('../assets/samsung_qled_q60t.jpeg'),
  },
  {
    id: '9',
    product_category: 'Watches',
    brand: 'Rolex',
    model: 'Submariner',
    condition: 'Used - Excellent',
    price: '$8000',
    image: require('../assets/rolex_submariner.jpeg'),
  },
  {
    id: '10',
    product_category: 'Watches',
    brand: 'Omega',
    model: 'Seamaster',
    condition: 'Used - Good',
    price: '$3500',
    image: require('../assets/omega_seamaster.jpeg'),
  },
];
